/** Base URL for gift folder on Bunny CDN (no trailing slash). */
function getGiftAssetBase(): string {
  const runtimeEnv = (window as any).__ENV;
  const toAbs = (value?: string): string => {
    if (!value || !String(value).trim()) return '';
    let url = String(value).trim().replace(/\/+$/, '');
    if (!url.startsWith('http://') && !url.startsWith('https://')) url = `https://${url}`;
    return url;
  };

  const cdnUrl = toAbs((import.meta.env.VITE_CDN_URL || runtimeEnv?.VITE_CDN_URL) as string | undefined);
  const bunnyCdn = toAbs((import.meta.env.VITE_BUNNY_CDN_HOSTNAME || runtimeEnv?.VITE_BUNNY_CDN_HOSTNAME) as string | undefined);
  const bunnyCdnNonVite = toAbs((import.meta.env.BUNNY_CDN_HOSTNAME || runtimeEnv?.BUNNY_CDN_HOSTNAME) as string | undefined);
  const giftBase = toAbs((import.meta.env.VITE_GIFT_ASSET_BASE_URL || runtimeEnv?.VITE_GIFT_ASSET_BASE_URL) as string | undefined);

  const preferred = cdnUrl || bunnyCdn || bunnyCdnNonVite || 'https://elixstorage.b-cdn.net';
  if (giftBase && !giftBase.includes('storage.bunnycdn.com')) return giftBase;
  return preferred;
}

/** Full URL for a gift asset (PNG icon or MP4/WebM video). Path e.g. "/gifts/Horse.png" or "gifts/Horse.mp4". */
export function resolveGiftAssetUrl(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) {
    try {
      const parsed = new URL(path);
      if (parsed.hostname === 'storage.bunnycdn.com') {
        const base = getGiftAssetBase();
        const trimmedPath = parsed.pathname.startsWith('/') ? parsed.pathname.slice(1) : parsed.pathname;
        return `${base}/${trimmedPath}`;
      }
    } catch {
      // keep original if URL parsing fails
    }
    return path;
  }
  const base = getGiftAssetBase();
  if (!base) return path.startsWith('/') ? path : `/${path}`;
  const trimmed = path.startsWith('/') ? path.slice(1) : path;
  return `${base}/${trimmed}`;
}

const giftUrl = (path: string) => resolveGiftAssetUrl(path); 
 
 export type GiftType = 'universe' | 'big' | 'small'; 
 
 export type GiftItem = { 
   id: string; 
   name: string; 
   coins: number; 
   giftType: GiftType; 
   isActive: boolean; 
   icon: string; 
   video: string; 
   preview: string; 
 }; 
 
 export const GIFTS: GiftItem[] = [ 
   // --- Small Gifts (Static) --- 
   { 
     id: 's_rose', 
     name: 'Red Rose', 
     coins: 1, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/740/740935.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/740/740935.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/740/740935.png', 
   }, 
   { 
     id: 's_heart', 
     name: 'Love Heart', 
     coins: 5, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/833/833472.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/833/833472.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/833/833472.png', 
   }, 
   { 
     id: 's_coffee', 
     name: 'Morning Coffee', 
     coins: 15, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/924/924514.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/924/924514.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/924/924514.png', 
   }, 
   { 
     id: 's_diamond', 
     name: 'Blue Diamond', 
     coins: 300, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png', 
   }, 
   { 
     id: 's_crown', 
     name: 'King Crown', 
     coins: 1500, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/691/691065.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/691/691065.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/691/691065.png', 
   }, 
   { 
     id: 's_panda', 
     name: 'Cute Panda', 
     coins: 10, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png', 
   }, 
   { 
     id: 's_butterfly', 
     name: 'Blue Butterfly', 
     coins: 25, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png', 
   }, 
   { 
     id: 's_cat', 
     name: 'Happy Cat', 
     coins: 50, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/616/616430.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/616/616430.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/616/616430.png', 
   }, 
   { 
     id: 's_dog', 
     name: 'Puppy Love', 
     coins: 100, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/194/194279.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/194/194279.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/194/194279.png', 
   }, 
   { 
     id: 's_sun', 
     name: 'Sunny Day', 
     coins: 250, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/869/869869.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/869/869869.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/869/869869.png', 
   }, 
   { 
     id: 's_rainbow', 
     name: 'Rainbow', 
     coins: 500, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/265/265674.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/265/265674.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/265/265674.png', 
   }, 
   { 
     id: 's_unicorn', 
     name: 'Mini Unicorn', 
     coins: 1000, 
     giftType: 'small', 
     isActive: true, 
     icon: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png', 
     video: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png', 
     preview: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png', 
   }, 
 
   // --- Video Gifts (Auto-generated from public/gifts) --- 
   { 
     id: 'global_universe', 
     name: 'Global Universe', 
     coins: 1000000, 
     giftType: 'universe', 
     isActive: true, 
     icon: giftUrl('/gifts/elix_global_universe.png'), 
     video: giftUrl('/gifts/elix_global_universe.webm'), 
     preview: giftUrl('/gifts/elix_global_universe.png'), 
   }, 
 
  
 
 
  { 
    id: 'horse_gallop', 
    name: 'Galloping Horse', 
    coins: 5000, 
    giftType: 'big', 
    isActive: true, 
    icon: giftUrl('/gifts/Horse.png'), 
    video: giftUrl('/gifts/Horse.mp4'), 
    preview: giftUrl('/gifts/Horse.png'), 
  }, 
  { 
    id: 'rex_dino', 
     name: 'T-Rex', 
     coins: 12000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/rex_dinosaur.png'), 
     video: giftUrl('/gifts/rex_dinosaur.mp4'), 
     preview: giftUrl('/gifts/rex_dinosaur.png'), 
   }, 
   { 
     id: 'treasure_chest', 
     name: 'Treasure Chest', 
     coins: 15000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/a_gleaming_treasure_chest_in_a_cave.png'), 
     video: giftUrl('/gifts/a_gleaming_treasure_chest_in_a_cave.mp4'), 
     preview: giftUrl('/gifts/a_gleaming_treasure_chest_in_a_cave.png'), 
   }, 
   { 
     id: 'war_bird', 
     name: 'War Bird', 
     coins: 15000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/fantasy_celestial_war_bird.png'), 
     video: giftUrl('/gifts/fantasy_celestial_war_bird.mp4'), 
     preview: giftUrl('/gifts/fantasy_celestial_war_bird.png'), 
   }, 
   { 
     id: 'kitty_treasure', 
     name: 'Kitty Treasure', 
     coins: 17000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/crown_kitty_treasure.png'), 
     video: giftUrl('/gifts/crown_kitty_treasure.mp4'), 
     preview: giftUrl('/gifts/crown_kitty_treasure.png'), 
   }, 
   { 
     id: 'frost_wolf', 
     name: 'Frost Wolf', 
     coins: 18000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/frost_wolf.png'), 
     video: giftUrl('/gifts/frost_wolf.mp4'), 
     preview: giftUrl('/gifts/frost_wolf.png'), 
   }, 
   { 
     id: 'voyager_ship', 
     name: 'Voyager Ship', 
     coins: 19000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/crystal_voyager_ship.png'), 
     video: giftUrl('/gifts/crystal_voyager_ship.mp4'), 
     preview: giftUrl('/gifts/crystal_voyager_ship.png'), 
   }, 
   { 
     id: 'fiery_lion', 
     name: 'Fiery Lion', 
     coins: 21000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/fiery_lion_in_blazing_glory.png'), 
     video: giftUrl('/gifts/fiery_lion_in_blazing_glory.mp4'), 
     preview: giftUrl('/gifts/fiery_lion_in_blazing_glory.png'), 
   }, 
   { 
     id: 'night_panther', 
     name: 'Night Panther', 
     coins: 22000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/night_panther.png'), 
     video: giftUrl('/gifts/night_panther.mp4'), 
     preview: giftUrl('/gifts/night_panther.png'), 
   }, 
   { 
     id: 'titan_gorilla', 
     name: 'Titan Gorilla', 
     coins: 23000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/earth_titan_gorilla.png'), 
     video: giftUrl('/gifts/earth_titan_gorilla.mp4'), 
     preview: giftUrl('/gifts/earth_titan_gorilla.png'), 
   }, 
   { 
     id: 'misty_wolf', 
     name: 'Misty Wolf', 
     coins: 25000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/ferocious_wolf_in_misty_terrain.png'), 
     video: giftUrl('/gifts/ferocious_wolf_in_misty_terrain.mp4'), 
     preview: giftUrl('/gifts/ferocious_wolf_in_misty_terrain.png'), 
   }, 
   { 
     id: 'cosmic_panther', 
     name: 'Cosmic Panther', 
     coins: 26000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/cosmic_panther.png'), 
     video: giftUrl('/gifts/cosmic_panther.mp4'), 
     preview: giftUrl('/gifts/cosmic_panther.png'), 
   }, 
   { 
     id: 'star_wand', 
     name: 'Star Wand', 
     coins: 28000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/celestial_star_wand.png'), 
     video: giftUrl('/gifts/celestial_star_wand.mp4'), 
     preview: giftUrl('/gifts/celestial_star_wand.png'), 
   }, 
   { 
     id: 'beast_relic', 
     name: 'Beast Relic', 
     coins: 31000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/beast_relic_of_the_ancients.png'), 
     video: giftUrl('/gifts/beast_relic_of_the_ancients.webm'), 
     preview: giftUrl('/gifts/beast_relic_of_the_ancients.png'), 
   }, 
   { 
     id: 'crystal_rhino', 
     name: 'Crystal Rhino', 
     coins: 32000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/crystal_rhino.png'), 
     video: giftUrl('/gifts/crystal_rhino.mp4'), 
     preview: giftUrl('/gifts/crystal_rhino.png'), 
   }, 
   { 
     id: 'storm_phoenix', 
     name: 'Storm Phoenix', 
     coins: 34000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/arcane_storm_phoenix.png'), 
     video: giftUrl('/gifts/arcane_storm_phoenix.mp4'), 
     preview: giftUrl('/gifts/arcane_storm_phoenix.png'), 
   }, 
   { 
     id: 'ice_sorceress', 
     name: 'Ice Sorceress', 
     coins: 37000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/elix_ice_sorceress.png'), 
     video: giftUrl('/gifts/elix_ice_sorceress.mp4'), 
     preview: giftUrl('/gifts/elix_ice_sorceress.png'), 
   }, 
   { 
     id: 'fire_phoenix', 
     name: 'Fire Phoenix', 
     coins: 38000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/fire_phoenix.png'), 
     video: giftUrl('/gifts/fire_phoenix.mp4'), 
     preview: giftUrl('/gifts/fire_phoenix.png'), 
   }, 
   { 
     id: 'lavarok', 
     name: 'Lavarok', 
     coins: 40000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/lavarok.png'), 
     video: giftUrl('/gifts/lavarok.mp4'), 
     preview: giftUrl('/gifts/lavarok.png'), 
   }, 
   { 
     id: 'blazing_wizard', 
     name: 'Blazing Wizard', 
     coins: 42000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/fiery_power_of_the_blazing_wizard.png'), 
     video: giftUrl('/gifts/fiery_power_of_the_blazing_wizard.mp4'), 
     preview: giftUrl('/gifts/fiery_power_of_the_blazing_wizard.png'), 
   }, 
   { 
     id: 'aelyra_flameveil', 
     name: 'Aelyra Flameveil', 
     coins: 45000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/aelyra_flameveil.png'), 
     video: giftUrl('/gifts/aelyra_flameveil.mp4'), 
     preview: giftUrl('/gifts/aelyra_flameveil.png'), 
   }, 
   { 
     id: 'golden_lion', 
     name: 'Golden Lion', 
     coins: 46000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/golden_rage_lion.png'), 
     video: giftUrl('/gifts/golden_rage_lion.mp4'), 
     preview: giftUrl('/gifts/golden_rage_lion.png'), 
   }, 
   { 
     id: 'dragon_egg', 
     name: 'Dragon Egg', 
     coins: 49000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/ember_dragon_egg.png'), 
     video: giftUrl('/gifts/ember_dragon_egg.mp4'), 
     preview: giftUrl('/gifts/ember_dragon_egg.png'), 
   }, 
   { 
     id: 'lava_demon', 
     name: 'Lava Demon', 
     coins: 52000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/lava_demon.png'), 
     video: giftUrl('/gifts/lava_demon.mp4'), 
     preview: giftUrl('/gifts/lava_demon.png'), 
   }, 
   { 
     id: 'dragon_wrath', 
     name: 'Dragon Wrath', 
     coins: 55000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/dragon_s_wrath_ride.png'), 
     video: giftUrl('/gifts/dragon_s_wrath_ride.mp4'), 
     preview: giftUrl('/gifts/dragon_s_wrath_ride.png'), 
   }, 
   { 
     id: 'flames_royalty', 
     name: 'Flames Royalty', 
     coins: 55000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/flames_and_royalty_on_fiery_ground.png'), 
     video: giftUrl('/gifts/flames_and_royalty_on_fiery_ground.mp4'), 
     preview: giftUrl('/gifts/flames_and_royalty_on_fiery_ground.png'), 
   }, 
   { 
     id: 'fire_unicorn', 
     name: 'Fire Unicorn', 
     coins: 55000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/mythic_fire_unicorn.png'), 
     video: giftUrl('/gifts/mythic_fire_unicorn.mp4'), 
     preview: giftUrl('/gifts/mythic_fire_unicorn.png'), 
   }, 
   { 
     id: 'thunder_falcon', 
     name: 'Thunder Falcon', 
     coins: 58000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/elix_thunder_falcon.png'), 
     video: giftUrl('/gifts/elix_thunder_falcon.mp4'), 
     preview: giftUrl('/gifts/elix_thunder_falcon.png'), 
   }, 
   { 
     id: 'infernal_lion', 
     name: 'Infernal Lion', 
     coins: 60000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/infernal_lion_king.png'), 
     video: giftUrl('/gifts/infernal_lion_king.mp4'), 
     preview: giftUrl('/gifts/infernal_lion_king.png'), 
   }, 
   { 
     id: 'fantasy_unicorn', 
     name: 'Fantasy Unicorn', 
     coins: 61000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/fantasy_unicorn.png'), 
     video: giftUrl('/gifts/fantasy_unicorn.mp4'), 
     preview: giftUrl('/gifts/fantasy_unicorn.png'), 
   }, 
   { 
     id: 'sky_guardian', 
     name: 'Sky Guardian', 
     coins: 64000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/eternal_guardian.png'), 
     video: giftUrl('/gifts/eternal_guardian.mp4'), 
     preview: giftUrl('/gifts/eternal_guardian.png'), 
   }, 
   { 
     id: 'majestic_bird', 
     name: 'Majestic Bird', 
     coins: 65000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/majestic_ice_blue_mythic_bird.png'), 
     video: giftUrl('/gifts/majestic_ice_blue_mythic_bird.mp4'), 
     preview: giftUrl('/gifts/majestic_ice_blue_mythic_bird.png'), 
   }, 
   { 
     id: 'flame_king', 
     name: 'The Flame King', 
     coins: 65000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/the_flame_king.png'), 
     video: giftUrl('/gifts/the_flame_king.mp4'), 
     preview: giftUrl('/gifts/the_flame_king.png'), 
   }, 
   { 
     id: 'majestic_phoenix', 
     name: 'Majestic Phoenix', 
     coins: 70000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/majestic_phoenix_soaring_in_flames.png'), 
     video: giftUrl('/gifts/majestic_phoenix_soaring_in_flames.mp4'), 
     preview: giftUrl('/gifts/majestic_phoenix_soaring_in_flames.png'), 
   }, 
   { 
     id: 'molten_fury', 
     name: 'Molten Fury', 
     coins: 75000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/molten_fury_of_the_lava_dragon.png'), 
     video: giftUrl('/gifts/molten_fury_of_the_lava_dragon.mp4'), 
     preview: giftUrl('/gifts/molten_fury_of_the_lava_dragon.png'), 
   }, 
   { 
     id: 'universe', 
     name: 'Universe', 
     coins: 80000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/elix_live_universe.png'), 
     video: giftUrl('/gifts/elix_live_universe.webm'), 
     preview: giftUrl('/gifts/elix_live_universe.png'), 
   }, 
   { 
     id: 'lava_rampage', 
     name: 'Lava Rampage', 
     coins: 80000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/rampage_of_the_lava_beast.png'), 
     video: giftUrl('/gifts/rampage_of_the_lava_beast.mp4'), 
     preview: giftUrl('/gifts/rampage_of_the_lava_beast.png'), 
   }, 
   { 
     id: 'guardian_chest', 
     name: 'Guardian Chest', 
     coins: 85000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/legendary_guardians_of_treasure_chest.png'), 
     video: giftUrl('/gifts/legendary_guardians_of_treasure_chest.mp4'), 
     preview: giftUrl('/gifts/legendary_guardians_of_treasure_chest.png'), 
   }, 
   { 
     id: 'storm_warrior', 
     name: 'Storm Warrior', 
     coins: 85000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/storm_warrior_in_electric_fury.png'), 
     video: giftUrl('/gifts/storm_warrior_in_electric_fury.mp4'), 
     preview: giftUrl('/gifts/storm_warrior_in_electric_fury.png'), 
   }, 
   { 
     id: 'pink_jet', 
     name: 'Pink Love Jet', 
     coins: 88000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/pink_love_jet.png'), 
     video: giftUrl('/gifts/pink_love_jet.mp4'), 
     preview: giftUrl('/gifts/pink_love_jet.png'), 
   }, 
   { 
     id: 'frost_lion', 
     name: 'Frost Lion', 
     coins: 90000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/froststorm_lion.png'), 
     video: giftUrl('/gifts/froststorm_lion.mp4'), 
     preview: giftUrl('/gifts/froststorm_lion.png'), 
   }, 
   { 
     id: 'night_owl', 
     name: 'Night Owl', 
     coins: 90000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/stormborn_night_owl.png'), 
     video: giftUrl('/gifts/stormborn_night_owl.mp4'), 
     preview: giftUrl('/gifts/stormborn_night_owl.png'), 
   }, 
   { 
     id: 'drake_cub', 
     name: 'Drake Cub', 
     coins: 95000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/treasure_drake_cub.png'), 
     video: giftUrl('/gifts/treasure_drake_cub.mp4'), 
     preview: giftUrl('/gifts/treasure_drake_cub.png'), 
   }, 
   { 
     id: 'romantic_jet', 
     name: 'Romantic Jet', 
     coins: 99000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/romantic_jet.png'), 
     video: giftUrl('/gifts/romantic_jet.mp4'), 
     preview: giftUrl('/gifts/romantic_jet.png'), 
   }, 
   { 
     id: 'guardian_vault', 
     name: 'Guardian Vault', 
     coins: 100000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/mythic_beast_vault_phoenix_lion_dragon_bear_wolf.png'), 
     video: giftUrl('/gifts/mythic_beast_vault_phoenix_lion_dragon_bear_wolf.mp4'), 
     preview: giftUrl('/gifts/mythic_beast_vault_phoenix_lion_dragon_bear_wolf.png'), 
   }, 
   { 
     id: 'elix_gold_universe', 
     name: 'Gold Universe', 
     coins: 120000, 
     giftType: 'big', 
     isActive: true, 
     icon: giftUrl('/gifts/elix_gold_universe.png'), 
     video: giftUrl('/gifts/elix_gold_universe.webm'), 
     preview: giftUrl('/gifts/elix_gold_universe.png'), 
   },  
  { 
    id: 'lightning_hypercar', 
    name: 'Lightning Car', 
    coins: 150000, 
    giftType: 'big', 
    isActive: true, 
    icon: giftUrl('/gifts/lightning_hypercar.png'), 
    video: giftUrl('/gifts/lightning_hypercar.mp4'), 
    preview: giftUrl('/gifts/lightning_hypercar.png'), 
  }, 
       ]; 

/** Max combo multiplier on the gift combo button (counts 1 … this value). */
export const GIFT_COMBO_MAX = 5000;
